doc: add homekit known issues
greg-fer/fw-nrfconnect-nrf-1 pull request #11
Opened 2021-12-07 23:54 UTC by b-gent

Moving homekit known issues from private docset to main NCS docs.

Signed-off-by: Bartosz Gentkowski <bartosz.gentkowski@nordicsemi.no>

2021-12-08 10:09 UTC, mariuszpos commented on doc/nrf/known_issues.rst
> +The HAP tools ``provision`` command freezes when EUI argument is not passed in attempt to read EUI from a connected board.
for Mac OS only

2021-12-08 12:45 UTC, greg-fer requested changes
Please add JIRA numbers to known issues, to have a "title + description" formatting for them.

2021-12-08 14:24 UTC, b-gent commented on doc/nrf/known_issues.rst
> +The HAP tools ``provision`` command freezes when EUI argument is not passed in attempt to read EUI from a connected board.
added

2021-12-08 14:28 UTC, b-gent commented
@greg-fer I added the Jira numbers and implemented the comment from Mariusz, this is good to go.

2021-12-08 14:34 UTC, b-gent commented
For two of the issue , I am unable to provide a more detailed description to have the title + description format.
Maybe @mariuszpos  could help

2021-12-09 07:18 UTC, greg-fer approved these changes

2021-12-09 07:18 UTC, merged